---
fail_fast: false
default_stages:
  - commit
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.13.0
    hooks:
      - id: pyupgrade
        args:
          - --keep-runtime-typing

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args:
          - --profile=black

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
        args:
          - --config=pyproject.toml

  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        exclude: .*/__init__.py
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.10.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix]
        files: toml

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - id: ruff
        args:
          - --config
          - ./pyproject.toml
          - --fix

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        types:
          - python
        args:
          - -c
          - pyproject.toml
          - --quiet
        additional_dependencies:
          - bandit[toml]
          - toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies:
          - mypy-extensions
          - pydantic==1.10.12
          - pytest~=7.3.1
          - httpx~=0.18.2
          - pydiction~=0.1.0
          - pytest-asyncio~=0.21.0




  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-symlinks
      - id: check-toml
      - id: debug-statements
      - id: no-commit-to-branch
        args:
          - --branch
          - main


  - repo: local
    hooks:
      - id: poetry-lock
        name: poetry-install
        description: run poetry install to install dependencies from the lock file
        entry: poetry lock
        args:
          - --no-update
        language: python
        pass_filenames: false
        files: pyproject.toml

      - id: poetry-install
        name: poetry-install
        description: run poetry install to install dependencies from the lock file
        entry: poetry install
        args:
          - --no-root
        language: python
        pass_filenames: false
        stages: [post-checkout, post-merge]
        always_run: true


  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args:
          - --offset
          - '2'
          - --mapping
          - '2'
          - --sequence
          - '4'


  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17  # Use the ref you want to point at
    hooks:
      - id: mdformat
      # Optionally add plugins
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
