---
fail_fast: false
default_stages:
  - commit
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.13.0
    hooks:
      - id: pyupgrade
        args:
          - --keep-runtime-typing

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args:
          - --profile=black


  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
        args:
          - --config=pyproject.toml

  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        exclude: .*/__init__.py
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables

#  - repo: https://github.com/pre-commit/mirrors-autopep8
#    rev: v2.0.4
#    hooks:
#      - id: autopep8

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - id: ruff
        args:
          - --config
          - ./pyproject.toml
          - --fix

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        types:
          - python
        args:
          - -c
          - pyproject.toml
          - --quiet
        additional_dependencies:
          - bandit[toml]
          - toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies:
          - mypy-extensions
          - pydantic==1.10.12
          - pytest~=7.3.1
          - httpx~=0.18.2
          - pydiction~=0.1.0
          - pytest-asyncio~=0.21.0




  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-symlinks
      - id: check-toml
      - id: debug-statements
      - id: no-commit-to-branch
        args:
          - --branch
          - master


  - repo: https://github.com/python-poetry/poetry
    rev: 1.4.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args:
          - --no-update
          #      - id: poetry-export


  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args:
          - --offset
          - '2'
          - --mapping
          - '2'
          - --sequence
          - '4'
