---
site_name: pydangORM
theme:
  name: material
  features:
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - Documentation:
      Vertex: orm/vertex.md
      Edge: orm/edge.md
      Collection Config: orm/collection.md
      Query: orm/query.md
      Session: session.md
  - API:
      Query Core (Low Level):
        Usage: query/usage.md
        Expressions: query/expressions.md
        Functions: query/functions.md
        Options: query/options.md
        Operations: query/operations.md
        Query: query/query.md

repo_url: https://github.com/nadobando/pydangorm
repo_name: nadobando/pydangorm

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details

  - pymdownx.tasklist:
      custom_checkbox: true
